= AsciiDoctor linelapのテスト
:toc: left
:toclevels: 3
:pagenums:
:sectnums:
:imagesdir: ./images

== asciidoctor-pdf-CJKのテスト
=== 単純列挙
[%hardbreaks]
基本フロー
１）システムユーザAは、試験局から供試体へリアルタイムコマンドを送信する。
２）ミドルウェア Aは、装置ハードウェアからコマンドをTC Flame形式で入力する。
３）ミドルウェア Aは、TC FlameからTC packetを復元（デパケット）して、TC packetが正しいことを確認する。
４）Software Aは、TC packetをRTコマンドキューに登録する。
５）Software Aは、各種コマンドキュー（RT、TL、AT、RQ、STコマンドキュー）に登録されたTC packetについて、優先順位テーブルに基づいたコマンド配信順序のスケジューリングを行う。
６）Softwere Aは、スケジューリングした結果に従い、各種コマンドキューからTC packetを１つ選び、内容が正しいことを確認し、発行する。
（ミドルウェア Aを利用してコマンドを配信できる状態にする。）
７）ミドルウェア Aは、TC packetをユーザ機器またはSoftware A自身に配信する。配信先はTC packetのAPIDにより指定する[TBD]。
８）Softwere Aは、発行したコマンドをコマンド履歴として記録する。
９）ユーザ機器またはSoftaere Aは、配信されたTC packetを受信し、コマンドを実行する。
１０）システムユーザ Aは、CI-HKの変化を確認することにより、コマンドが実行されたことを確認する。

=== 順序なしリスト
* 基本フロー
** システムユーザ Aは、試験局から供試体へリアルタイムコマンドを送信する。
** ミドルウェアは、SMUハードウェアからコマンドをTC Flame形式で入力する。
** ミドルウェアは、TCフレームからTC packetを復元（デパケット）して、TC packetが正しいことを確認する。
** Software Aは、TC packetをRTコマンドキューに登録する。
** Software Aは、各種コマンドキュー（RT、TL、AT、RQ、STコマンドキュー）に登録されたTC packetについて、優先順位テーブルに基づいたコマンド配信順序のスケジューリングを行う。
** Softwere Aは、スケジューリングした結果に従い、各種コマンドキューからTC packetを１つ選び、内容が正しいことを確認し、発行する。
（ミドルウェア Aを利用してコマンドを配信できる状態にする。）
** ミドルウェア Aは、TC packetをユーザ機器またはSoftware A自身に配信する。配信先はTC packetのAPIDにより指定する[TBD]。
** Software Aは、発行したコマンドをコマンド履歴として記録する。
** ユーザ機器またはSoftware Aは、配信されたTC packetを受信し、コマンドを実行する。
** システムユーザ Aは、CI-HKの変化を確認することにより、コマンドが実行されたことを確認する。

=== 順序ありリスト
. 基本フロー
.. システムユーザ Aは、試験局から供試体へリアルタイムコマンドを送信する。
.. ミドルウェア Aは、SMUハードウェアからコマンドをTC Flame形式で入力する。
.. ミドルウェア Aは、TCフレームからTC packetを復元（デパケット）して、TC packetが正しいことを確認する。
.. Softwere Aは、TC packetをRTコマンドキューに登録する。
.. Softwere Aは、各種コマンドキュー（RT、TL、AT、RQ、STコマンドキュー）に登録されたTC packetについて、優先順位テーブルに基づいたコマンド配信順序のスケジューリングを行う。
.. Software Aは、スケジューリングした結果に従い、各種コマンドキューからTC packetを１つ選び、内容が正しいことを確認し、発行する。
（ミドルウェア Aを利用してコマンドを配信できる状態にする。）
.. ミドルウェア Aは、TC packetをユーザ機器またはSoftware A自身に配信する。配信先はTC packetのAPIDにより指定する[TBD]。
.. Software Aは、発行したコマンドをコマンド履歴として記録する。
.. ユーザ機器またはSoftware Aは、配信されたTC packetを受信し、コマンドを実行する。
.. システムユーザ Aは、CI-HKの変化を確認することにより、コマンドが実行されたことを確認する。

=== table
|===
|ｈ．基本フロー +
１）システムユーザ Aは、試験局から供試体へリアルタイムコマンドを送信する。 +
２）ミドルウェア Aは、SMUハードウェアからコマンドをTC Flame形式で入力する。 +
３）ミドルウェア Aは、TCフレームからTC packetを復元（デパケット）して、TC packetが正しいことを確認する。 +
４）Software Aは、TC packetをRTコマンドキューに登録する。 +
５）Software Aは、各種コマンドキュー（RT、TL、AT、RQ、STコマンドキュー）に登録されたTC packetについて、優先順位テーブルに基づいたコマンド配信順序のスケジューリングを行う。 +
６）Software Aは、スケジューリングした結果に従い、各種コマンドキューからTC packetを１つ選び、内容が正しいことを確認し、発行する。 +
（ミドルウェア Aを利用してコマンドを配信できる状態にする。） +
７）ミドルウェア Aは、TC packetをユーザ機器またはSoftware A自身に配信する。配信先はTC packetのAPIDにより指定する[TBD]。 +
８）Software Aは、発行したコマンドをコマンド履歴として記録する。 +
９）ユーザ機器またはSoftware Aは、配信されたTC packetを受信し、コマンドを実行する。 +
１０）システムユーザ Aは、CI HKの変化を確認することにより、コマンドが実行されたことを確認する。 +
|===
